### ISSUE TITLE
cdrom issue with PAL 5502

### ISSUE THREAD

**Issue by mgarcia-org** [ShendoXT/ps1cardlink#2]
Hi Shendo,
I burnt your cue/bin image from: http://shendosoft.blogspot.com/2014/01/memcardrex-18-released.html
But couldn't get the program to work, I know it works on emulation.
I can make my own PSX CD images, so I extracted your system.cnf/CARDLINK.EXE and made my own but that too also didn't work :/

On my hardware it shows the black SCEE Playstation screen really glitchy and then goes into a black screen with a small white box at the top left corner.

Any ideas?
Thanks 
Mike.

**Comment by ShendoXT** [comment]
Sorry, I have no idea why that would be the case... Are you able to launch .exe via other means?
Since ps1cardlink uses serial I'll assume you have a serial cable. Are you able to launch the exe with PSXSERIAL?

**Comment by mgarcia-org** [comment]
Hi,
Your right, I sent CARDLINK.EXE using SIOLOAD and worked first time!
Closed.
