### ISSUE TITLE
hack image writing

### ISSUE THREAD

**Issue by mgarcia-org** [ShendoXT/ps1cardlink#3]
Have you tried writing a hack image, ie: https://github.com/brad-lin/FreePSXBoot
I tried writing an image via dexdrive and it didn't work, in the tabs they look the same, but looking using a hex editor, they're different.

**Comment by ShendoXT** [comment]
Have you used the latest version of MemcardRex from [here](https://github.com/ShendoXT/memcardrex/releases)?

MemcardRex used to correct corrupt data which FreePSXBoot relies upon. In the latest version that is turned off and is user selectable in the preferences window.

**Comment by mgarcia-org** [comment]
I downloaded it from your website.
Very cool, thanks! :)

**Comment by mgarcia-org** [comment]
sorry for posting on ps1link
FYI,  MemcardRex 1.9.2b7a018 doesn't run in winXP, not a valid win32 app.
The hack image update 1.9 works fine :)

**Comment by ShendoXT** [comment]
Yes. MemcardRex now has .NET 4.5 dependency because libusbdotnet requires it for PS3 Memory Card adapter and .NET 4.5 is not supported on Windows XP.

Previous 1.9 pre-release requires .NET 4.0 and MemcardRex 1.8 requires 3.5 which are both still supported on Windows Xp.
